# Generated by Django 5.0.7 on 2024-08-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument_type',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Drums', 'Drums'), ('Violin', 'Violin'), ('Flute', 'Flute')], max_length=10),
        ),
    ]
